corpora:
    # ilci:
    #     splits: ['train']
    #     # langs: [ 'en', 'hi',  'ta', 'te', 'ml', 'ur', 'bn']
    #     langs: ['en', 'hi']
        # langs: ['en', 'hi']
        # wat-ilmpc:
        # wat-splits: ['dev']
        # wat-langs: ['en', 'ta']
    # iitb-hi-en:
    #     splits: ['train', 'dev', 'test']
    #     langs: ['en', 'hi']
    # wat-ilmpc:
    #     splits: ['train', 'dev', 'test']
    #     # langs: [ 'en', 'hi',  'ta', 'te', 'ml', 'ur', 'bn']
    #     langs: ['en', 'ta']
    # national-newscrawl:
    #     splits: ['train']
    #     langs: ['en', 'hi']
    # ufal-en-tam:
    #     splits: ['train', 'test', 'dev']
    #     langs: ['en', 'ta']
    # mechturk-en-te:
    #     splits: ['train', 'dev', 'test']
    #     langs: ['en', 'te']
    # complete-en-te:
    #     splits: ['train', 'dev', 'test']
    #     langs: ['en', 'te']
    # complete-en-ml:
    #     splits: ['train', 'dev', 'test']
    #     langs: ['en', 'ml']
    europarl-en-fr:
        splits: ['train', 'dev', 'test']
        langs: ['en', 'fr']
    # pib-en-mar:
    #    splits: ['train','dev','test']
    #    langs: ['en','mr']
    # pretrain-en-tam:
    #     splits: ['train', 'dev']
    #     langs: ['en', 'ta']
    

dictionary_og:
    src: '/content/drive/My Drive/RA-Project-IIIT-H/Cat_Forgetting/ilmulti-master/resources/cat_forgetting_dicts/en-es.dict.txt'
    tgt: '/content/drive/My Drive/RA-Project-IIIT-H/Cat_Forgetting/ilmulti-master/resources/cat_forgetting_dicts/en-es.dict.txt'

dictionary_comb:
    src: '/content/drive/My Drive/RA-Project-IIIT-H/Cat_Forgetting/ilmulti-master/resources/cat_forgetting_dicts/en-fr-es.dict.txt'
    tgt: '/content/drive/My Drive/RA-Project-IIIT-H/Cat_Forgetting/ilmulti-master/resources/cat_forgetting_dicts/en-fr-es.dict.txt'

# dictionary_comb:
#     src: '/content/drive/My Drive/RA-Project-IIIT-H/Cat_Forgetting/ilmulti-master/resources/cat_forgetting_dicts/en-es.dict.txt'
#     tgt: '/content/drive/My Drive/RA-Project-IIIT-H/Cat_Forgetting/ilmulti-master/resources/cat_forgetting_dicts/en-es.dict.txt'


hard_coded_dict: {
    'en': 8000,
    'fr': 8000
}
